In [1]:
import pandas as pd
import folium

In [2]:
df= pd.read_excel('big-mac-2019-01-01.xls')

In [4]:
df.shape

(56, 18)

In [9]:
df.head(50)

,Country,iso_a3,currency_code,local_price,dollar_ex,dollar_price,dollar_ppp,GDP_dollar,dollar_valuation,euro_valuation,sterling_valuation,yen_valuation,yuan_valuation,dollar_adj_valuation,euro_adj_valuation,sterling_adj_valuation,yen_adj_valuation,yuan_adj_valuation
0,United Arab Emirates,ARE,AED,14.00,3.673150,3.811442,2.508961,NaN,-31.7,-17.9,-6.4,6.0,24.9,NaN,NaN,NaN,NaN,NaN
1,Argentina,ARG,ARS,75.00,37.455000,2.002403,13.440860,14462.920000,-64.1,-56.9,-50.8,-44.3,-34.4,-41.9,-43.4,-33.8,-26.1,-39.6
2,Australia,AUS,AUD,6.10,1.401640,4.352045,1.093190,55692.730000,-22.0,-6.2,6.9,21.0,42.6,-19.2,-21.3,-8.0,2.8,-16.0
3,Azerbaijan,AZE,AZN,3.95,1.696500,2.328323,0.707885,NaN,-58.3,-49.8,-42.8,-35.3,-23.7,NaN,NaN,NaN,NaN,NaN
4,Bahrain,BHR,BHD,1.20,0.377000,3.183024,0.215054,NaN,-43.0,-31.4,-21.9,-11.5,4.3,NaN,NaN,NaN,NaN,NaN
5,Brazil,BRA,BRL,16.90,3.717950,4.545516,3.028674,9895.765000,-18.5,-2.1,11.6,26.4,49.0,40.6,37.0,60.1,78.9,46.3
6,Canada,CAN,CAD,6.77,1.331400,5.084873,1.213262,45094.605000,-8.9,9.5,24.8,41.4,66.7,4.0,1.3,18.5,32.3,8.2
7,Switzerland,CHE,CHF,6.50,0.981650,6.621505,1.164875,80637.381000,18.7,42.6,62.6,84.1,117.0,0.9,-1.7,15.0,28.4,5.0
8,Chile,CHL,CLP,2640.00,678.990000,3.888128,473.118280,15067.724000,-30.3,-16.2,-4.5,8.1,27.4,11.8,9.0,27.4,42.3,16.4
9,China,CHN,CNY,20.90,6.849700,3.051229,3.745520,8643.107000,-45.3,-34.3,-25.1,-15.2,0.0,-3.9,-6.3,9.5,22.3,0.0
10,Colombia,COL,COP,11900.00,3191.500000,3.728654,2132.616487,6379.606000,-33.2,-19.7,-8.5,3.7,22.2,21.5,18.4,38.4,54.6,26.4
11,Costa Rica,CRI,CRC,2290.00,606.975000,3.772808,410.394265,NaN,-32.4,-18.7,-7.4,4.9,23.6,NaN,NaN,NaN,NaN,NaN
12,Czech Republic,CZE,CZK,85.00,22.311650,3.809669,15.232975,20401.577000,-31.7,-17.9,-6.5,5.9,24.9,2.2,-0.4,16.4,30.1,6.3
13,Denmark,DNK,DKK,30.00,6.515450,4.604440,5.376344,56630.596000,-17.5,-0.8,13.0,28.0,50.9,-15.2,-17.4,-3.4,7.9,-11.8
14,Egypt,EGY,EGP,40.00,17.910000,2.233389,7.168459,2495.020000,-60.0,-51.9,-45.2,-37.9,-26.8,-22.6,-24.6,-11.8,-1.5,-19.5
15,Euro area,EUZ,EUR,4.05,0.872486,4.641908,0.725806,37309.093379,-16.8,0.0,14.0,29.1,52.1,2.6,0.0,16.9,30.6,6.8
16,Britain,GBR,GBP,3.19,0.783208,4.072992,0.571685,39800.274000,-27.0,-12.3,0.0,13.3,33.5,-12.2,-14.5,0.0,11.7,-8.7
17,Guatemala,GTM,GTQ,25.00,7.728300,3.234864,4.480287,NaN,-42.0,-30.3,-20.6,-10.1,6.0,NaN,NaN,NaN,NaN,NaN
18,Hong Kong,HKG,HKD,20.00,7.834350,2.552860,3.584229,46080.481000,-54.2,-45.0,-37.3,-29.0,-16.3,-48.3,-49.6,-41.1,-34.2,-46.2
19,Honduras,HND,HNL,85.00,24.339100,3.492323,15.232975,NaN,-37.4,-24.8,-14.3,-2.9,14.5,NaN,NaN,NaN,NaN,NaN
20,Croatia,HRV,HRK,21.00,6.478850,3.241316,3.763441,NaN,-41.9,-30.2,-20.4,-9.9,6.2,NaN,NaN,NaN,NaN,NaN
21,Hungary,HUN,HUF,850.00,280.268750,3.032803,152.329749,14209.443000,-45.6,-34.7,-25.5,-15.7,-0.6,-11.7,-14.0,0.5,12.3,-8.2
22,Indonesia,IDN,IDR,33000.00,14090.000000,2.342087,5913.978495,3875.769000,-58.0,-49.5,-42.5,-34.9,-23.2,-20.6,-22.7,-9.6,1.0,-17.4
23,India,IND,INR,178.00,69.685000,2.554352,31.899642,1976.093000,-54.2,-45.0,-37.3,-29.0,-16.3,-10.7,-13.0,1.7,13.6,-7.1
24,Israel,ISR,ILS,17.00,3.707850,4.584867,3.046595,40272.966000,-17.8,-1.2,12.6,27.5,50.3,-1.7,-4.2,12.0,25.1,2.3
25,Jordan,JOR,JOD,1.95,0.709600,2.748027,0.349462,NaN,-50.8,-40.8,-32.5,-23.6,-9.9,NaN,NaN,NaN,NaN,NaN
26,Japan,JPN,JPY,390.00,108.440000,3.596459,69.892473,38448.569000,-35.5,-22.5,-11.7,0.0,17.9,-21.4,-23.4,-10.5,0.0,-18.2
27,South Korea,KOR,KRW,4500.00,1118.600000,4.022886,806.451613,29938.450000,-27.9,-13.3,-1.2,11.9,31.8,-3.7,-6.1,9.7,22.6,0.2
28,Kuwait,KWT,KWD,1.05,0.303100,3.464203,0.188172,NaN,-37.9,-25.4,-14.9,-3.7,13.5,NaN,NaN,NaN,NaN,NaN
29,Lebanon,LBN,LBP,6500.00,1507.000000,4.313205,1164.874552,NaN,-22.7,-7.1,5.9,19.9,41.4,NaN,NaN,NaN,NaN,NaN
30,Sri Lanka,LKA,LKR,580.00,182.245000,3.182529,103.942652,NaN,-43.0,-31.4,-21.9,-11.5,4.3,NaN,NaN,NaN,NaN,NaN
31,Moldova,MDA,MDL,40.00,17.263000,2.317094,7.168459,NaN,-58.5,-50.1,-43.1,-35.6,-24.1,NaN,NaN,NaN,NaN,NaN
32,Mexico,MEX,MXN,49.00,19.308750,2.537710,8.781362,9318.823000,-54.5,-45.3,-37.7,-29.4,-16.8,-20.8,-22.9,-9.8,0.7,-17.7
33,Malaysia,MYS,MYR,9.05,4.117500,2.197936,1.621864,9755.178000,-60.6,-52.7,-46.0,-38.9,-28.0,-31.9,-33.6,-22.4,-13.3,-29.1
34,Nicaragua,NIC,NIO,103.00,32.360700,3.182873,18.458781,NaN,-43.0,-31.4,-21.9,-11.5,4.3,NaN,NaN,NaN,NaN,NaN
35,Norway,NOR,NOK,50.00,8.532900,5.859673,8.960573,75389.460000,5.0,26.2,43.9,62.9,92.0,-7.2,-9.6,5.7,18.1,-3.4
36,New Zealand,NZL,NZD,6.20,1.479290,4.191200,1.111111,41572.269000,-24.9,-9.7,2.9,16.5,37.4,-11.3,-13.5,1.1,12.9,-7.7
37,Oman,OMN,OMR,1.05,0.384900,2.727981,0.188172,NaN,-51.1,-41.2,-33.0,-24.1,-10.6,NaN,NaN,NaN,NaN,NaN
38,Pakistan,PAK,PKR,460.00,138.880000,3.312212,82.437276,1545.938000,-40.6,-28.6,-18.7,-7.9,8.6,16.6,13.6,32.8,48.4,21.3
39,Peru,PER,PEN,10.50,3.348500,3.135732,1.881720,6731.851000,-43.8,-32.4,-23.0,-12.8,2.8,1.7,-1.0,15.8,29.4,5.8
40,Philippines,PHL,PHP,140.00,52.392500,2.672138,25.089606,2988.897000,-52.1,-42.4,-34.4,-25.7,-12.4,-8.1,-10.5,4.7,16.9,-4.4
41,Poland,POL,PLN,10.50,3.748450,2.801158,1.881720,13821.233000,-49.8,-39.7,-31.2,-22.1,-8.2,-18.0,-20.2,-6.6,4.3,-14.7
42,Qatar,QAT,QAR,12.00,3.641250,3.295572,2.150538,NaN,-40.9,-29.0,-19.1,-8.4,8.0,NaN,NaN,NaN,NaN,NaN
43,Romania,ROU,RON,9.30,4.066950,2.286726,1.666667,NaN,-59.0,-50.7,-43.9,-36.4,-25.1,NaN,NaN,NaN,NaN,NaN
44,Russia,RUS,RUB,110.17,66.685000,1.652096,19.743728,10955.792000,-70.4,-64.4,-59.4,-54.1,-45.9,-49.7,-51.0,-42.7,-36.0,-47.6
45,Saudi Arabia,SAU,SAR,12.00,3.751150,3.199019,2.150538,21096.440000,-42.7,-31.1,-21.5,-11.1,4.8,-14.9,-17.1,-3.1,8.3,-11.5
46,Singapore,SGP,SGD,5.80,1.355900,4.277602,1.039427,57713.335000,-23.3,-7.8,5.0,18.9,40.2,-22.0,-24.0,-11.1,-0.7,-18.8
47,Sweden,SWE,SEK,52.00,8.906250,5.838596,9.318996,52925.128000,4.6,25.8,43.3,62.3,91.4,11.1,8.2,26.5,41.3,15.5
48,Thailand,THA,THB,119.00,32.007500,3.717879,21.326165,6590.638000,-33.4,-19.9,-8.7,3.4,21.8,20.8,17.7,37.6,53.7,25.7
49,Turkey,TUR,TRY,10.75,5.383400,1.996879,1.926523,10537.186000,-64.2,-57.0,-51.0,-44.5,-34.6,-38.8,-40.4,-30.3,-22.1,-36.3

In [6]:
df.describe()

,local_price,dollar_ex,dollar_price,dollar_ppp,GDP_dollar,dollar_valuation,euro_valuation,sterling_valuation,yen_valuation,yuan_valuation,dollar_adj_valuation,euro_adj_valuation,sterling_adj_valuation,yen_adj_valuation,yuan_adj_valuation
count,56.000000,56.000000,56.000000,56.000000,37.000000,56.000000,56.000000,56.000000,56.000000,56.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,2318.258214,816.129930,3.435738,415.458461,26446.440848,-38.423214,-25.980357,-15.646429,-4.473214,12.600000,-10.583784,-12.886486,1.854054,13.775676,-6.975676
std,9752.329576,3603.340077,1.091660,1747.729315,22516.292512,19.564671,23.513953,26.800305,30.353466,35.781854,20.227216,19.713900,23.034595,25.739511,21.046172
min,1.050000,0.303100,1.652096,0.188172,1545.938000,-70.400000,-64.400000,-59.400000,-54.100000,-45.900000,-49.700000,-51.000000,-42.700000,-36.000000,-47.600000
25%,9.237500,3.568062,2.553979,1.655466,8643.107000,-54.200000,-45.000000,-37.300000,-29.000000,-16.300000,-21.400000,-23.400000,-10.500000,0.000000,-18.200000
50%,30.500000,8.183625,3.238090,5.465950,15067.724000,-41.950000,-30.250000,-20.500000,-10.000000,6.100000,-11.300000,-13.500000,1.100000,12.900000,-7.700000
75%,124.250000,41.189375,4.102544,22.267025,41572.269000,-26.475000,-11.650000,0.725000,14.100000,34.475000,1.700000,-1.000000,15.800000,29.400000,5.800000
max,65000.000000,23199.000000,6.621505,11648.745520,80637.381000,18.700000,42.600000,62.600000,84.100000,117.000000,40.600000,37.000000,60.100000,78.900000,46.300000

In [8]:
df['Country']

KeyError: False

In [4]:
df = df.drop(['iso_a3', 'currency_code', 'local_price', 'yen_valuation','dollar_ex','dollar_ppp','euro_adj_valuation','yuan_valuation','sterling_valuation', 'GDP_dollar', 'dollar_valuation', 'yuan_adj_valuation','yen_adj_valuation','sterling_adj_valuation' ,'dollar_adj_valuation', 'euro_valuation'], axis=1)

In [5]:
df.head(5)

                Country  dollar_price
0  United Arab Emirates      3.811442
1             Argentina      2.002403
2             Australia      4.352045
3            Azerbaijan      2.328323
4               Bahrain      3.183024

In [7]:
import os

In [11]:
state_geo = os.path.join('../../folium/examples/data/', 'world-countries.json')

In [12]:
state_geo

'../../folium/examples/data/world-countries.json'

In [15]:
m = folium.Map(location=[-23, -46], zoom_start=3)
 
# Add the color for the chloropleth:
m.choropleth(
 geo_data=state_geo,
 name='choropleth',
 data=df,
 columns=['Country', 'dollar_price'],
 key_on='feature.properties.name',
 fill_color='YlGn',
 fill_opacity=0.7,
 line_opacity=0.2,
 legend_name='Big Mac Price'
)
folium.LayerControl().add_to(m)
 
# Save to html
m.save('folium_chloropleth_bigmac.html')

/home/tuts/anaconda3/lib/python3.6/site-packages/folium/folium.py:426: FutureWarning: The choropleth  method has been deprecated. Instead use the new Choropleth class, which has the same arguments. See the example notebook 'GeoJSON_and_choropleth' for how to do this.
  FutureWarning

In [16]:
df['Country']

0     United Arab Emirates
1                Argentina
2                Australia
3               Azerbaijan
4                  Bahrain
5                   Brazil
6                   Canada
7              Switzerland
8                    Chile
9                    China
10                Colombia
11              Costa Rica
12          Czech Republic
13                 Denmark
14                   Egypt
15               Euro area
16                 Britain
17               Guatemala
18               Hong Kong
19                Honduras
20                 Croatia
21                 Hungary
22               Indonesia
23                   India
24                  Israel
25                  Jordan
26                   Japan
27             South Korea
28                  Kuwait
29                 Lebanon
30               Sri Lanka
31                 Moldova
32                  Mexico
33                Malaysia
34               Nicaragua
35                  Norway
36             New Zealand
37                    Oman
38                Pakistan
39                    Peru
40             Philippines
41                  Poland
42                   Qatar
43                 Romania
44                  Russia
45            Saudi Arabia
46               Singapore
47                  Sweden
48                Thailand
49                  Turkey
50                  Taiwan
51                 Ukraine
52                 Uruguay
53           United States
54                 Vietnam
55            South Africa
Name: Country, dtype: object